### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shusain** [CodingTrain/Frogger#1]
Hey could you include some sort of license if it's okay for me to port this... I already did but will remove my port immediately if you didn't intend on open sourcing this.

https://github.com/shusain/FroggerOLED is the ported code so far I just moved it into C++ so it could be used on a particle.io board and modified the drawing functions to draw to the OLED display I had ordered but otherwise it is this code.

**Comment by meiamsome** [comment]
Thank you for raising this, it is certainly something relevant to do! This itself is a port of other code with a few modifications and I believe both Dan and I are fine with you having that repo there, it's great to see. If you are okay with it, I'll add a link to it in the readme in the repository so others can have a look aswell.
I would also love a link to a video of your hardware implementation out of interest!

@shiffman This is probably something that you should decide considering none of the projects on Coding Train are listed with any licensing information at all. Given how I perceive your intentions in this, I'd recommend the MIT License, but a good overview is available at https://choosealicense.com/ . If you chose a license I'd be happy to add it to whatever repositories require it for your convenience.

**Comment by shusain** [comment]
@meiamsome awesome, I figured based on the videos and @shiffman generally saying he wants people to run with it to mean that it's okay, but I always get nervous copying anything I find online that doesn't have a license on it of any sort.  Even a mention that it's free to copy is usually good enough for me but prefer to see MIT or something so I know it's fine for me to use.

Thanks for sharing the code I did post a little video of playing the game once here but didn't really give any explanation since I just wanted to post something quick to share with a buddy, but this is the link:

https://youtu.be/9RTrC0jM-hg

I'm gonna see if I can add some text and a few other things into here, but also need to see if anyone with experience with the particle.io photon board knows how I can properly break up the C++ files and get it to build (was having some weird linker problem so I just threw all the class definitions into one file).

**Comment by shiffman** [comment]
Thanks for this discussion! Yes, @meiamsome for all of my code examples I would choose MIT License. (Note I use a different license for The Nature of Code book itself -- Creative Commons non-commercial -- and would choose something different on a case by case basis for tools and written materials, but for example code it should be as free and flexible as possible!).

Definitely feel free to go and add MIT wherever you see fit.

**Comment by shiffman** [comment]
Also @shusain this is awesome, thanks for sharing!

**Comment by shiffman** [comment]
Sorry for the multiple messages, @shusain are you on twitter? I'd love to share this version and want to credit accordingly.

**Comment by shusain** [comment]
@shiffman no problem on sharing back. Gave me something fun to do with the screen I ordered for no reason :) .

I'm "on Twitter" as @ShaunHusain but I just use Twitter as a consumer never really post there, fine with getting queries that way though.

I'll add MIT to my source too.  Thanks again love the show and live sessions when I make it.
